webapp:
  name: skitunes
  group: skitunes
  fqdn: skitunes.gingmachine
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes:2024-10-16.18.42
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2