webapp:
  name: skitunes-dev
  group: skitunes
  activeHost: skitunes-dev.ging.nickknows.net
  previewHost: skitunes-dev-preview.ging.nickknows.net
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes-app:2025-01-17.19.37
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2
rollout:
  enabled: true
  autoPromotionEnabled: true