webapp:
  name: skitunes
  group: skitunes
  activeHost: skitunes.nickknows.net
  previewHost: skitunes-dev.nickknows.net
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes-app:2025-01-24.04.39
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2
rollout:
  enabled: true
  autoPromotionEnabled: true