webapp:
  name: skitunes-dev
  group: skitunes
  fqdn: skitunes-dev.gingmachine
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes:2024-10-16.18.53
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2
rollout:
  enabled: true
  autoPromotionEnabled: false