webapp:
  name: skitunes-dev
  group: skitunes
  activeHost: skitunes-dev.gingmachine
  previewHost: skitunes-dev-preview.gingmachine
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes-app:2024-12-02.20.24
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2
rollout:
  enabled: true
  autoPromotionEnabled: false