webapp:
    image: docker.io/ncging/skitunes:2024-11-27.22.31
    image: docker.io/ncging/skitunes:2024-11-27.22.31
    image: docker.io/ncging/skitunes:2024-11-27.22.31
    image: docker.io/ncging/skitunes:2024-11-27.22.31
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/skitunes:2024-11-27.22.31
    imagePullPolicy: Always
    port: 8000
worker:
  replicaCount: 2
rollout:
  enabled: true
  autoPromotionEnabled: false