"""add pending_entries and entry_votes tables

Revision ID: da9b7690a579
Revises: 
Create Date: 2026-03-02 08:32:28.089869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9b7690a579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.String(length=200), nullable=True),
    sa.Column('movie_year', sa.String(length=10), nullable=True),
    sa.Column('movie_co', sa.String(length=200), nullable=True),
    sa.Column('movie_img_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('pending_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.String(length=200), nullable=False),
    sa.Column('song_artist', sa.String(length=200), nullable=True),
    sa.Column('song_album', sa.String(length=200), nullable=True),
    sa.Column('song_num', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('spotify_id', sa.String(length=500), nullable=True),
    sa.Column('skier_name', sa.String(length=500), nullable=True),
    sa.Column('ski_type', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('video_link', sa.String(length=500), nullable=True),
    sa.Column('movie_name', sa.String(length=200), nullable=False),
    sa.Column('movie_year', sa.String(length=10), nullable=True),
    sa.Column('movie_co', sa.String(length=200), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.String(length=200), nullable=True),
    sa.Column('song_artist', sa.String(length=200), nullable=True),
    sa.Column('song_album', sa.String(length=200), nullable=True),
    sa.Column('song_num', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('spotify_id', sa.String(length=500), nullable=True),
    sa.Column('skier_name', sa.String(length=500), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('ski_type', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('video_link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pending_entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pending_entry_id'], ['pending_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pending_entry_id', 'user_id', name='uq_vote_per_user')
    )
    op.drop_table('Ski Movie Tunes Info')
    op.drop_table('movie_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_details',
    sa.Column('movie_id', sa.INTEGER(), nullable=False),
    sa.Column('Movie Name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Movie Year', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Production Company', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Movie Cover URL', sa.VARCHAR(length=100), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Ski Movie Tunes Info.id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('Ski Movie Tunes Info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Song Title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Song Artist', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Album', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Song Number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Genres', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Spotify Link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Skier Name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Primary Ski Style', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Link to segment', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry_votes')
    op.drop_table('songs')
    op.drop_table('pending_entries')
    op.drop_table('movies')
    # ### end Alembic commands ###
