apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.webapp.name }}-pgdb
  namespace: {{ .Release.Namespace }}
spec:  
    instances: 1
    storage:
      size: 5Gi
    storageClass: rook-cephfs