apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.webapp.name }}-pgdb
  namespace: {{ .Release.Namespace }}
spec:  
  instances: 1
  storage:
    size: 5Gi

  # Create a standard user from user_external_secret
  bootstrap:
    initdb:
      database: {{ .Values.db.app.name }}
      owner: {{ .Values.db.app.owner }}
      secret:
        name: {{ .Values.db.name }}-app-user