apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skitunes-esos
  namespace: skitunes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: skitunes-esos
  data:
  - secretKey: flask-secret
    remoteRef:
      key: skitunes       # Just the path without data/ prefix for v1
      property: flask-secret
  - secretKey: db-username
    remoteRef:
      key: skitunes       # Just the path without data/ prefix for v1
      property: db-username
  - secretKey: db-password
    remoteRef:
      key: skitunes       # Just the path without data/ prefix for v1
      property: db-password
  - secretKey: spotify-client-id
    remoteRef:
      key: spotify       # Just the path without data/ prefix for v1
      property: client-id
  - secretKey: spotify-client-secret
    remoteRef:
      key: spotify       # Just the path without data/ prefix for v1
      property: client-secret
  - secretKey: google-client-id
    remoteRef:
      key: google       # Just the path without data/ prefix for v1
      property: client-id
  - secretKey: google-client-id
    remoteRef:
      key: google       # Just the path without data/ prefix for v1
      property: client-secret