apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.db.name }}-app-user
  namespace: skitunes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: {{ .Values.db.name }}-app-user
  data:
  - secretKey: username
    remoteRef:
      key: skitunes
      property: db-username
  - secretKey: password
    remoteRef:
      key: skitunes
      property: db-password