apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ .Values.webapp.name }}-pgdb
    group: {{ .Values.webapp.group }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: {{ .Values.webapp.name }}-pgdb