apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    group: {{ .Values.webapp.group }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                name: flask-secret
                key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                name: flask-secret
                key: db-password
            - name: POSTGRES_DB
              value: "skitunes"
        - name: FLASK_SECRET
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: flask-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc