{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.webapp.name }}
  labels:
    app: {{ .Values.webapp.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.webapp.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
        name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        env:
        - name: FLASK_SECRET
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: flask-secret
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        resources:
          limits:
            cpu: '0'
            memory: '0'
  strategy:
    blueGreen:
      activeService: {{ .Values.webapp.name }}-active
      previewService: {{ .Values.webapp.name }}-preview
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled | default false }}
{{- end }}