apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
  annotations:
   traefik.ingress.kubernetes.io/router.entrypoints: websecure
   traefik.ingress.kubernetes.io/router.tls: "true"
   cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
   kubernetes.io/ingress-class: traefik
spec:
  tls:
    - hosts:
      - {{ .Values.webapp.previewHost}}
  rules:
  - host: {{ .Values.webapp.previewHost }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-preview
            port:
              number: {{ .Values.webapp.container.port }}