apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    kubernetes.io/ingress-class: nginx
    external-dns.alpha.kubernetes.io/target: "8.44.158.127"
spec:
  tls:
    - hosts:
      - {{ .Values.webapp.previewHost}}
      secretName: {{ .Values.webapp.previewHost}}-tls
  rules:
  - host: {{ .Values.webapp.previewHost }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-preview
            port:
              number: {{ .Values.webapp.container.port }}