apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
      - name: {{ .Values.webapp.name }}
        env:
        - name: FLASK_SECRET
          valueFrom:
            secretKeyRef:
              name: flask-secret-dev
              key: flask-secret
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        resources:
          limits:
            cpu: '0'
            memory: '0'